version: "3"

services:
  nodeos:
    container_name: nodeos
    build:
      context: ./nodeos
      dockerfile: Dockerfile
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - ./nodeos-data:/opt/eosio/bin/data-dir
      - ./nodeos-config:/opt/eosio/bin/config-dir